replicaCount: 2

image:
  repository: nginx
  tag: 1.21.1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  port: 80
  targetPort: 80

routes:
  - path: /auth
    serviceName: auth-svc
    servicePort: 80
  - path: /api
    serviceName: api-svc
    servicePort: 80
  - path: /frontend
    serviceName: frontend-svc
    servicePort: 80