
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-router-config
data:
  default.conf: |
    server {
      listen 80;
      {% for route in .Values.routes %}
      location {{ route.path }} {
        proxy_pass http://{{ route.serviceName }}:{{ route.servicePort }};
      }
      {% endfor %}
    }